import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dive Photos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={styles.grid}>
          <div className="image-container">
            <Image
              src="/Octopus7.jpg"
              height={900}
              width={1600}
              quality={100}
            />
          </div>
          <div className="image-container">
            <Image
              src="/Octopus7.jpg"
              height={900}
              width={1600}
              quality={100}
            />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Spencer</footer>
    </div>
  );
};

export default Home;
